language: node_js
node_js:
  - "7"
after_success:
  - # custom deploy
  - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
  - npm publish
  - # report test coverage
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info