language: node_js
node_js:
  - "7"
  - "8"
addons:
  code_climate:
    repo_token: 0bbce54299334e688fce4242faec765f21e9101430d8b948df590e9da4f54623
after_success:
  - # custom deploy
  - PACKAGE_NAME=${PWD##*/}
  - PUBLIC_VERSION=$(npm view $PACKAGE_NAME version)
  - PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
  - echo "$PACKAGE_VERSION $PUBLIC_VERSION $TRAVIS_BRANCH"
  - 'if [ "$PACKAGE_VERSION" != "$PUBLIC_VERSION" ] && [TRAVIS_BRANCH == "master"]; then
      echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      npm publish
    fi'
  - # report test coverage
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info